/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CesiumCesiumViewCesiumView: typeof import('./src/components/cesium/cesium-view/cesium-view.vue')['default']
    CesiumPopupImageMarker: typeof import('./src/components/cesium/popup/image-marker.vue')['default']
    CesiumPopupMarkerPopup: typeof import('./src/components/cesium/popup/marker-popup.vue')['default']
    CommonDialog: typeof import('./src/components/common/dialog/index.vue')['default']
    CommonHeader: typeof import('./src/components/common/header/index.vue')['default']
    CommonInput: typeof import('./src/components/common/input/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
